image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - eventyret.bootstrap-4-cdn-snippet@1.6.0:AtNd6GnbCYVpmUkOaFXs3A==
    - kevinglasson.cornflakes-linter@0.4.0:Sgfmpf9YWoF5/BDJu2xn0w==
    - lonefy.vscode-JS-CSS-HTML-formatter@0.2.3:i8S7423XUWOGOigQhW/Zbg==
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
    - CoenraadS.bracket-pair-colorizer-2@0.2.0:R8flOpw1fEZe6KyMNNNqBQ==